### ISSUE TITLE
Fetching embeddings with unexpected status code of 400 and 429

### ISSUE THREAD

**Issue by RayZhao1998** [copilot-extensions/rag-extension#2]
When I run this demo, I got errors like 400 or 429. Why does it happen and how to solve it?

```
failed to execute agent: error generating datasets: error creating embedding for file data/xxx.md: error fetching embeddings: unexpected status code: 400
```

**Comment by Houndie** [comment]
Unsure why you might get a 400...have you made any changes to the code or are you running it as is?

A 429 indicates a rate limiting error.

**Comment by Houndie** [comment]
But also:  We're closing issues in this repository in favor of accumulating them in https://github.com/copilot-extensions/user-feedback to help us stay on top of them.  Feel free to reopen an issue there if you still have quesitons!
